"""Update transaction model

Revision ID: 11210ff3ca69
Revises: 84bf6ed7bf9b
Create Date: 2025-06-05 07:37:37.314636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11210ff3ca69'
down_revision = '84bf6ed7bf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeframe', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('trade_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('entry_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('exit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('entry_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('exit_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('entry_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('exit_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trade_closed', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('stop_loss')
        batch_op.drop_column('amount')
        batch_op.drop_column('take_profit')
        batch_op.drop_column('leverage')
        batch_op.drop_column('type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('leverage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('take_profit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('stop_loss', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('trade_closed')
        batch_op.drop_column('profit_loss')
        batch_op.drop_column('exit_balance')
        batch_op.drop_column('entry_balance')
        batch_op.drop_column('exit_time')
        batch_op.drop_column('entry_time')
        batch_op.drop_column('exit_price')
        batch_op.drop_column('entry_price')
        batch_op.drop_column('trade_type')
        batch_op.drop_column('timeframe')

    # ### end Alembic commands ###
