"""add api credentials and balance to trading settings

Revision ID: 56cd64d79f7a
Revises: 7cc955fbe52e
Create Date: 2025-06-03 14:39:10.879129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cd64d79f7a'
down_revision = '7cc955fbe52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
