"""Add is_active to TradingSettings

Revision ID: 68093f3fe9ed
Revises: 73ee1ff7d56f
Create Date: 2025-06-14 20:13:55.550861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68093f3fe9ed'
down_revision = '73ee1ff7d56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
