"""Add atr_multiplier to TradingSettings

Revision ID: 73ee1ff7d56f
Revises: d16ebdf99b5b
Create Date: 2025-06-12 01:31:06.949252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee1ff7d56f'
down_revision = 'd16ebdf99b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atr_multiplier', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.drop_column('atr_multiplier')

    # ### end Alembic commands ###
