"""Add binance_active and telegram_active to TradingSettings

Revision ID: 7cc955fbe52e
Revises: 89404b9b891c
Create Date: 2025-05-20 16:22:41.170017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc955fbe52e'
down_revision = '89404b9b891c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binance_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('stop_loss',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('take_profit',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('take_profit',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('stop_loss',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('telegram_active')
        batch_op.drop_column('binance_active')

    # ### end Alembic commands ###
