"""add balance to user

Revision ID: 89404b9b891c
Revises: 
Create Date: 2025-05-06 03:22:32.288554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89404b9b891c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('stop_loss',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('take_profit',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('take_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('profit_loss')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_loss', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('take_profit')
        batch_op.drop_column('stop_loss')

    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.alter_column('take_profit',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('stop_loss',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('leverage',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
