"""Add atr_period to TradingSettings

Revision ID: d16ebdf99b5b
Revises: 11210ff3ca69
Create Date: 2025-06-12 01:30:18.826739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16ebdf99b5b'
down_revision = '11210ff3ca69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atr_period', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.drop_column('atr_period')

    # ### end Alembic commands ###
